# 端口配置
server:
  port: 8080
# 模板引擎配置
spring:
  thymeleaf:
    cache: false
    servlet:
      content-type: text/html
    enabled: true
    encoding: utf-8
    prefix: classpath:/templates/
    suffix: .html
  datasource:            # 数据源连接池  hikaricp
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.118.37.69:3306/myuser?serverTimezone=Asia/Shanghai
    username: root
    password: 12345678
    hikari:
      connection-timeout: 30000              # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQ
      minimum-idle: 5                        # 最小连接数
      maximum-pool-size: 20                  # 最大连接数
      auto-commit: true                      # 自动提交
      idle-timeout: 600000                   # 连接超时的最大时长（毫秒），超时则被释放（retired），默认:10分钟
      pool-name: DateSourceHikariCP          # 连接池名字
      max-lifetime: 1800000                  # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟
      connection-test-query: SELECT 1        # 连接的时候会有一个测试语句，直接去使用这个select 1去测试
  servlet:
    multipart:
      max-file-size: 512000                  # 文件上传大小限制为500kb
      max-request-size: 512000               # 请求大小限制为500kb


# mybatis相关配置
mybatis:
  type-aliases-package: com.ydbzs.pojo
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 3000
  mapper-locations: classpath:mapper/*.xml